### PR TITLE
Add Styling for Disabled Buttons

### PR DESCRIPTION
**Pull request by swissmanu**
hi @igoradamenko 

first of all: thank you for awsm.css! it is the perfect solution for simple, nice looking html rendering without the need of any fancy, huge css library. ❤️

this pull request contains a proposal for rendering disabled `button` elements so that the user can distinguish them from enabled ones.

i added a demo to the "Misc." section of the documentation. feel free to integrate the change if you like.

cheers,
@swissmanu

ps. i was not sure if you want contributions to contain builded versions of the change... let me know if you would prefer this.

### CODE REVIEW

**Comment by igoradamenko** [comment]
Hey there!

Thank you for your PR! You're right, I totally forgot about disabled buttons. And, yes, you should change just source files, the `dist/` folder will be updated right before publishing.

But would you mind if I replace your disabled button in “Misc.” section with disabled “Reset” button in “Mars vacation program” form, after merging your PR?

**Comment by swissmanu** [comment]
no problem at all. i just updated my commit so that the reset button is disabled.

**Comment by igoradamenko** [comment]
Great, thanks!

**Comment by igoradamenko** [comment]
Released as [awsm.css@3.0.6](https://www.npmjs.com/package/awsm.css/v/3.0.6).

Demo: https://igoradamenko.github.io/awsm.css/elements.html

**Pull request merged**
